const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = (minor,currency='USD') => new Intl.NumberFormat(state.locale,{style:'currency',currency}).format((minor||0)/100);
const date = (value) => value ? new Intl.DateTimeFormat(state.locale,{dateStyle:'medium'}).format(new Date(value)) : '—';
const copy = {
  en:{overview:'Overview',marketplace:'Marketplace',campaigns:'Campaigns',journeys:'Journeys',messaging:'Messaging',reports:'Reports',finance:'Finance',operations:'Operations',signOut:'Sign out',intro:'Plan and prove every placement',sub:'Discover verified inventory, book with confidence, and distinguish observed outcomes from reported ones.',newCampaign:'Create campaign',bookings:'Active bookings',spent:'Booked spend',leads:'Qualified leads',recent:'Recent activity',allCampaigns:'Campaigns',channelPerformance:'Channel performance',demo:'Sandbox workspace · no live sends or charges',empty:'Nothing here yet',catalog:'Explore inventory',switch:'Switch demo role',help:'Every figure shows its source and definition.'},
  fa:{overview:'نمای کلی',marketplace:'بازار رسانه',campaigns:'کمپین‌ها',journeys:'سفرها',messaging:'پیام‌رسانی',reports:'گزارش‌ها',finance:'مالی',operations:'عملیات',signOut:'خروج',intro:'برای هر جایگاه برنامه‌ریزی کنید و نتیجه را ثبت کنید',sub:'رسانه‌ها را کشف کنید، با اطمینان رزرو کنید و داده‌های مشاهده‌شده را از گزارش‌های دریافتی جدا ببینید.',newCampaign:'ایجاد کمپین',bookings:'رزروهای فعال',spent:'هزینه رزروشده',leads:'سرنخ‌های واجد شرایط',recent:'فعالیت اخیر',allCampaigns:'کمپین‌ها',channelPerformance:'عملکرد کانال',demo:'محیط آزمایشی · بدون ارسال یا پرداخت واقعی',empty:'هنوز داده‌ای وجود ندارد',catalog:'جستجوی رسانه',switch:'تغییر نقش آزمایشی',help:'منبع و تعریف هر عدد مشخص است.'}
};
const state={locale:localStorage.getItem('relay_locale')||'en',view:'overview',search:'',user:null,users:[],campaigns:[],bookings:[],catalog:[],report:null,activity:[],finance:null,review:null,reconciliation:null,properties:[],permissions:[],messages:[],message:'',error:''};
const t=(key)=>copy[state.locale][key]||key;
async function api(path,options={}){const res=await fetch(path,{credentials:'same-origin',headers:{'content-type':'application/json'},...options});const data=await res.json();if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`);return data;}
const post=(path,data={})=>api(path,{method:'POST',body:JSON.stringify(data)});
async function load(){try{state.user=await api('/api/me');}catch{state.user=null;}if(!state.user){state.users=await api('/api/demo-users');render();return;}const calls=[api('/api/catalog'),api('/api/bookings'),api('/api/report'),api('/api/activity'),api('/api/finance')];const [catalog,bookings,report,activity,finance]=await Promise.all(calls);Object.assign(state,{catalog,bookings,report,activity,finance});state.campaigns=state.user.role==='advertiser'?await api('/api/campaigns'):[];state.properties=state.user.role==='owner'?await api('/api/properties'):[];[state.review,state.reconciliation]=state.user.role==='operator'?await Promise.all([api('/api/review'),api('/api/reconciliation')]):[null,null];[state.permissions,state.messages]=state.user.role==='advertiser'?await Promise.all([api('/api/permissions'),api('/api/messages')]):[[],[]];render();}
function notice(){return state.message||state.error?`<div class="notice ${state.error?'error':''}" role="status">${escapeHtml(state.error||state.message)}<button data-action="dismiss" aria-label="Dismiss">×</button></div>`:'';}
function shell(content){const nav=[['overview',t('overview')],['marketplace',t('marketplace')],['campaigns',t('campaigns')],['journeys',t('journeys')],['messaging',t('messaging')],['reports',t('reports')],['finance',t('finance')],['operations',t('operations')]];return `<div class="shell" dir="${state.locale==='fa'?'rtl':'ltr'}"><aside class="sidebar"><div class="brand">Relay<span class="brand-mark">●</span></div><nav aria-label="Main navigation">${nav.map(([key,label])=>`<button class="nav-link ${state.view===key?'active':''}" data-view="${key}"><span class="nav-icon">${({overview:'⌂',marketplace:'◉',campaigns:'▣',journeys:'⌁',messaging:'✉',reports:'▥',finance:'▤',operations:'⚙'})[key]}</span>${label}</button>`).join('')}</nav><div class="side-bottom"><p>${t('demo')}</p><button class="text-button" data-action="logout">${t('signOut')}</button></div></aside><div class="workspace"><header class="topbar"><label class="top-search"><span aria-hidden="true">⌕</span><input id="global-search" type="search" aria-label="Search campaigns and inventory" placeholder="Search campaigns and inventory…" value="${escapeHtml(state.search)}"></label><div class="top-actions"><button class="lang" data-action="locale" aria-label="Change language">${state.locale==='en'?'فارسی':'English'}</button><div class="avatar">${escapeHtml(state.user.name.split(' ').map(x=>x[0]).join(''))}</div><div class="user-meta"><strong>${escapeHtml(state.user.name)}</strong><span>${escapeHtml(state.user.role)} · ${escapeHtml(state.user.orgId.replace('org_demo_',''))}</span></div></div></header><main id="main">${notice()}${content}</main></div></div>`;}
function metric(label,value,source,detail){return `<div class="metric"><div class="metric-value">${value}</div><div class="metric-label">${label}</div><div class="metric-source">${source} <span>· ${detail}</span></div></div>`;}
function pill(status){return `<span class="status status-${escapeHtml(status)}">${escapeHtml(status.replaceAll('_',' '))}</span>`;}
function campaignTable(){const rows=state.campaigns.filter(c=>`${c.name} ${c.objective} ${c.status}`.toLowerCase().includes(state.search.toLowerCase()));if(!rows.length)return empty(state.search?'No matching campaigns.':'No campaigns yet. Create one to begin.');return `<div class="table-wrap"><table><thead><tr><th>Campaign</th><th>Objective</th><th>Status</th><th>Budget</th><th>Created</th><th>Next step</th></tr></thead><tbody>${rows.map(c=>`<tr><td><strong>${escapeHtml(c.name)}</strong><small>${escapeHtml(c.id)}</small></td><td>${escapeHtml(c.objective)}</td><td>${pill(c.status)}</td><td>${money(c.budget_minor,c.currency)}</td><td>${date(c.created_at)}</td><td>${c.status==='draft'?`<button class="row-action" data-action="submit" data-id="${c.id}">Submit for review →</button>`:c.status==='approved'?`<button class="row-action" data-view="marketplace">Choose inventory →</button>`:'—'}</td></tr>`).join('')}</tbody></table></div>`;}
function bookingTable(){if(!state.bookings.length)return empty('No bookings yet. Approved campaigns can reserve inventory.');return `<div class="table-wrap"><table><thead><tr><th>Placement</th><th>Campaign</th><th>Status</th><th>Price</th><th>Proof and link</th><th>Action</th></tr></thead><tbody>${state.bookings.map(b=>`<tr><td><strong>${escapeHtml(b.inventory_name)}</strong><small>${escapeHtml(b.property_name)}</small></td><td>${escapeHtml(b.campaign_name)}</td><td>${pill(b.status)}</td><td>${money(b.price_minor,b.currency)}</td><td>${b.proof_url?`<a href="${escapeHtml(b.proof_url)}" target="_blank" rel="noopener noreferrer">Owner proof ↗</a><small>Owner reported</small>`:'—'}${b.tracking_url?`<a href="${escapeHtml(b.tracking_url)}" target="_blank" rel="noopener noreferrer">Tracked link ↗</a>`:''}</td><td>${bookingActions(b)}</td></tr>`).join('')}</tbody></table></div>`;}
function bookingActions(b){const parts=[];if(state.user.role==='owner'&&b.status==='reserved')parts.push(`<button class="row-action" data-action="accept" data-id="${b.id}">Accept →</button>`);if(state.user.role==='owner'&&b.status==='accepted')parts.push(`<button class="row-action" data-action="publish" data-id="${b.id}">Add proof →</button>`);if(state.user.role==='operator'&&b.status==='published')parts.push(`<button class="row-action" data-action="settle" data-id="${b.id}">Settle →</button>`);if(state.user.role==='operator'&&b.status==='disputed')parts.push(`<button class="row-action" data-action="resolve" data-id="${b.id}">Resolve →</button>`);if(['published','settled'].includes(b.status)&&state.user.role==='advertiser')parts.push(`<button class="row-action" data-action="conversion" data-id="${b.id}">Add conversion →</button>`);if(['published','settled'].includes(b.status)&&state.user.role!=='owner')parts.push(`<button class="row-action" data-action="invoice" data-id="${b.id}">Invoice →</button>`);if(b.status==='published'&&state.user.role!=='operator')parts.push(`<button class="row-action muted" data-action="dispute" data-id="${b.id}">Dispute</button>`);return parts.join(' ')||'—';}
function empty(message){return `<div class="empty"><div class="empty-symbol">◇</div><p>${escapeHtml(message)}</p></div>`;}
function overview(){const active=state.bookings.filter(b=>['reserved','accepted','published','disputed'].includes(b.status));const booked=state.bookings.reduce((n,b)=>n+(b.status==='cancelled'?0:b.price_minor),0);const leads=state.report?.rows.reduce((n,r)=>n+r.qualified_leads,0)||0;const currency=state.bookings[0]?.currency||'USD';return `<div class="page-heading"><div><p class="greeting">${state.user.role==='owner'?'Your media workspace':state.user.role==='operator'?'Review and reconciliation':'Welcome back, '+escapeHtml(state.user.name.split(' ')[0])}</p><h1>${t('intro')}</h1><p class="lead">${t('sub')}</p></div>${state.user.role==='advertiser'?`<button class="primary" data-action="new-campaign">${t('newCampaign')} <span>↗</span></button>`:''}</div><div class="overview-grid"><div class="main-column"><section class="metrics" aria-label="Key metrics">${metric(t('bookings'),active.length,'Contract state','not delivered exposure')}${metric(t('spent'),money(booked,currency),'Ledger contract','booked value')}${metric(t('leads'),leads,'Imported','advertiser submitted')}</section><section class="section"><div class="section-head"><h2>${state.user.role==='advertiser'?t('allCampaigns'):'Bookings'}</h2><button class="subtle-button" data-view="${state.user.role==='advertiser'?'campaigns':'journeys'}">View all →</button></div>${state.user.role==='advertiser'?campaignTable():bookingTable()}</section><section class="section"><div class="section-head"><div><h2>${t('channelPerformance')}</h2><p>Observed clicks and imported qualified leads by booked placement</p></div><button class="subtle-button" data-view="reports">Metric definitions →</button></div>${reportTable()}</section></div><aside class="activity-panel"><h2>${t('recent')}</h2><p class="activity-filter">All activity</p>${state.activity.length?`<ol class="activity-list">${state.activity.slice(0,7).map(a=>`<li><span class="activity-dot"></span><div><strong>${escapeHtml(a.action.replaceAll('.',' '))}</strong><small>${escapeHtml(a.target_id)}</small><time>${date(a.created_at)}</time></div></li>`).join('')}</ol>`:empty('Actions appear here as the sandbox journey progresses.')}<button class="subtle-button" data-view="operations">View operations →</button></aside></div>`;}
function reportTable(){const rows=state.report?.rows||[];if(!rows.length)return empty('Reports appear after a booking.');return `<div class="table-wrap"><table><thead><tr><th>Placement</th><th>Channel</th><th>Status</th><th>Booked spend</th><th>Clicks ⓘ</th><th>Qualified leads ⓘ</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${escapeHtml(r.campaign)}</strong><small>${escapeHtml(r.inventory)}</small></td><td>${escapeHtml(r.channel)}</td><td>${pill(r.status)}</td><td>${money(r.price_minor,r.currency)}</td><td>${r.clicks}</td><td>${r.qualified_leads}</td></tr>`).join('')}</tbody></table></div>`;}
function marketplace(){const rows=state.catalog.filter(i=>`${i.property_name} ${i.channel} ${i.format} ${i.description}`.toLowerCase().includes(state.search.toLowerCase()));return `<div class="simple-heading"><h1>${t('marketplace')}</h1><p>Verified or manually reviewed inventory. Proof and delivery terms remain visible through settlement.</p></div><div class="catalog-list">${rows.map(i=>`<article class="catalog-item"><div><p class="catalog-channel">${escapeHtml(i.channel)} · ${escapeHtml(i.format.replaceAll('_',' '))}</p><h2>${escapeHtml(i.property_name)}</h2><p>${escapeHtml(i.description)}</p><div class="fine">${pill(i.verification)} · Owner audience stays with the owner</div></div><div class="catalog-buy"><strong>${money(i.price_minor,i.currency)}</strong><small>Fixed placement · sandbox</small>${state.user.role==='advertiser'?`<button class="primary small" data-action="book" data-id="${i.id}">Book placement →</button>`:''}</div></article>`).join('')||empty(state.search?'No matching inventory.':'No listed inventory.')}</div>${state.user.role==='owner'?`<div class="section-actions"><button class="outline" data-action="new-property">Add property</button><button class="outline" data-action="new-inventory">Add inventory</button></div>`:''}`;}
function campaigns(){return `<div class="simple-heading"><h1>${t('campaigns')}</h1><p>Campaign approval, budget, and placement status are tracked separately.</p></div>${state.user.role==='advertiser'?`<div class="section-actions"><button class="primary" data-action="new-campaign">${t('newCampaign')}</button></div>${campaignTable()}`:bookingTable()}`;}
function journeys(){return `<div class="simple-heading"><h1>${t('journeys')}</h1><p>A redirect is an anonymous click. Conversions here are advertiser submitted claims linked to a booking; they do not prove identity or causality.</p></div>${bookingTable()}<div class="explainer"><h2>Evidence trail</h2><p>Owner publication proof → opaque redirect token → platform observed click → advertiser imported conversion → sandbox invoice and settlement.</p></div>`;}
function messaging(){if(state.user.role!=='advertiser')return `<div class="simple-heading"><h1>${t('messaging')}</h1><p>Advertiser-owned contact permissions remain separate from publisher audiences.</p></div>${empty('Only advertiser workspaces can use the messaging sandbox.')}`;return `<div class="simple-heading"><h1>${t('messaging')}</h1><p>Test-only SMS. No network message is sent. Grant documented permission, preflight segments and quiet hours, then record a sandbox acceptance.</p></div><div class="section-actions"><button class="primary" data-action="grant-permission">Record permission</button><button class="outline" data-action="sms-preflight">Preflight SMS</button><button class="outline" data-action="sms-send">Record test send</button><button class="text-button" data-action="withdraw-permission">Withdraw</button></div><section class="section"><h2>Permissions</h2><div class="table-wrap"><table><thead><tr><th>Channel</th><th>Purpose</th><th>Status</th><th>Proof source</th><th>Captured</th></tr></thead><tbody>${state.permissions.map(p=>`<tr><td>${escapeHtml(p.channel)}</td><td>${escapeHtml(p.purpose)}</td><td>${pill(p.status)}</td><td>${escapeHtml(p.proof_source)}</td><td>${date(p.captured_at)}</td></tr>`).join('')}</tbody></table></div>${state.permissions.length?'':empty('No permissions recorded.')}</section><section class="section"><h2>Sandbox messages</h2><div class="table-wrap"><table><thead><tr><th>Created</th><th>Channel</th><th>Purpose</th><th>Status</th><th>Estimate</th><th>Source</th></tr></thead><tbody>${state.messages.map(m=>`<tr><td>${date(m.created_at)}</td><td>${escapeHtml(m.channel)}</td><td>${escapeHtml(m.purpose)}</td><td>${pill(m.status)}</td><td>${money(m.estimate_minor,m.currency)}</td><td>Sandbox provider</td></tr>`).join('')}</tbody></table></div>${state.messages.length?'':empty('No sandbox sends recorded.')}</section>`;}
function reports(){return `<div class="simple-heading"><h1>${t('reports')}</h1><p>Fresh as of ${date(state.report?.asOf)} · UTC · sandbox data only</p></div>${reportTable()}<section class="definitions"><h2>Metric dictionary</h2>${Object.entries(state.report?.definitions||{}).map(([key,value])=>`<div><strong>${escapeHtml(key.replaceAll('_',' '))}</strong><span>${escapeHtml(value.definition)}</span><small>${escapeHtml(value.source)}</small></div>`).join('')}</section>`;}
function finance(){const entries=state.finance?.entries||[];return `<div class="simple-heading"><h1>${t('finance')}</h1><p>Balanced immutable postings in integer minor units. All records are sandbox entries; no payment or payout is made.</p></div><div class="table-wrap"><table><thead><tr><th>When</th><th>Reference</th><th>Account</th><th>Amount</th><th>Currency</th></tr></thead><tbody>${entries.map(e=>`<tr><td>${date(e.created_at)}</td><td><code>${escapeHtml(e.ref)}</code></td><td>${escapeHtml(e.account)}</td><td class="numeric ${e.amount<0?'negative':''}">${e.amount<0?'−':'+'}${money(Math.abs(e.amount),e.currency)}</td><td>${escapeHtml(e.currency)}</td></tr>`).join('')}</tbody></table></div>${entries.length?'':empty('No ledger entries.')}`;}
function operations(){
  if(state.user.role!=='operator')return `<div class="simple-heading"><h1>${t('operations')}</h1><p>Your activity and booking exceptions.</p></div>${bookingTable()}`;
  const reconciliation=state.reconciliation||{rows:[],discrepancyCount:0};
  return `<div class="simple-heading"><h1>${t('operations')}</h1><p>Review campaigns and properties before they become bookable. Settle only after owner reported proof.</p></div>
    <section class="reconciliation"><div><strong>Internal sandbox reconciliation</strong><p>${reconciliation.rows.length} booking(s) checked · ${reconciliation.discrepancyCount} ${reconciliation.discrepancyCount===1?'discrepancy':'discrepancies'} · external providers not reconciled</p></div>${pill(reconciliation.discrepancyCount?'needs_review':'balanced')}</section>
    <div class="ops-grid"><section><h2>Campaign review</h2>${(state.review?.campaigns||[]).map(c=>`<div class="review-row"><div><strong>${escapeHtml(c.name)}</strong><small>${escapeHtml(c.objective)} · ${money(c.budget_minor,c.currency)}</small></div><div><button class="outline small" data-action="review-campaign-approve" data-id="${c.id}">Approve</button><button class="text-button" data-action="review-campaign-reject" data-id="${c.id}">Reject</button></div></div>`).join('')||empty('Queue clear.')}</section><section><h2>Property review</h2>${(state.review?.properties||[]).map(p=>`<div class="review-row"><div><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.channel)} · ownership evidence pending</small></div><div><button class="outline small" data-action="review-property-approve" data-id="${p.id}">Manual review</button><button class="text-button" data-action="review-property-reject" data-id="${p.id}">Reject</button></div></div>`).join('')||empty('Queue clear.')}</section></div><section class="section"><h2>Settlement queue</h2>${bookingTable()}</section>`;
}
function render(){document.documentElement.lang=state.locale;document.documentElement.dir=state.locale==='fa'?'rtl':'ltr';if(!state.user){$('#app').innerHTML=`<div class="login-page" dir="${state.locale==='fa'?'rtl':'ltr'}"><div class="login-panel"><div class="brand">Relay<span class="brand-mark">●</span></div><h1>Every placement, accounted for.</h1><p>Choose a sandbox role to run the entire booking, proof, measurement, and settlement journey. No live providers are connected.</p><div class="role-list">${state.users.map(u=>`<button data-action="login" data-id="${u.id}"><span class="role-avatar">${escapeHtml(u.name.split(' ').map(x=>x[0]).join(''))}</span><span><strong>${escapeHtml(u.name)}</strong><small>${escapeHtml(u.role)} · ${escapeHtml(u.email)}</small></span><span>→</span></button>`).join('')}</div><button class="lang" data-action="locale">${state.locale==='en'?'فارسی':'English'}</button>${notice()}</div><div class="login-art"><div class="orbit"><div class="orbit-center">Relay</div><span>Discover</span><span>Book</span><span>Measure</span><span>Settle</span></div></div></div>`;return;}const views={overview,marketplace,campaigns,journeys,messaging,reports,finance,operations};$('#app').innerHTML=shell(views[state.view]());}
function modal(title,fields,submit){state.message='';state.error='';const overlay=document.createElement('div');overlay.className='modal-backdrop';overlay.innerHTML=`<div class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-head"><h2 id="modal-title">${escapeHtml(title)}</h2><button type="button" class="close" aria-label="Close dialog">×</button></div><form id="modal-form">${fields}<div class="modal-actions"><button type="button" class="outline close">Cancel</button><button class="primary" type="submit">Continue →</button></div></form></div>`;document.body.append(overlay);overlay.querySelector('input,select,button')?.focus();overlay.querySelectorAll('.close').forEach(x=>x.addEventListener('click',()=>overlay.remove()));overlay.addEventListener('click',e=>{if(e.target===overlay)overlay.remove();});overlay.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{await submit(data);overlay.remove();state.message=state.message||'Saved in sandbox';state.error='';await load();}catch(error){overlay.querySelectorAll('.form-error').forEach(x=>x.remove());overlay.querySelector('.modal-actions').insertAdjacentHTML('beforebegin',`<p class="form-error">${escapeHtml(error.message)}</p>`);}});}
const field=(name,label,type='text',value='',extra='')=>`<label class="field"><span>${label}</span><input name="${name}" type="${type}" value="${escapeHtml(value)}" required ${extra}></label>`;
function chooseBooking(skuId){const approved=state.campaigns.filter(c=>c.status==='approved');if(!approved.length){state.error='Create and obtain approval for a campaign first.';render();return;}modal('Book this placement',`<label class="field"><span>Approved campaign</span><select name="campaignId">${approved.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('')}</select></label><p class="field-help">Reservation moves sandbox funds into escrow. The media owner must accept and publish proof.</p>`,d=>post('/api/bookings',{campaignId:d.campaignId,inventoryId:skuId}));}
const smsFields=(withBody=true)=>field('to','Test contact (E.164)','tel','+15551234567')+field('purpose','Permission purpose','text','demo_offer')+(withBody?field('body','SMS text','text','Hello from Relay sandbox')+field('timeZone','Contact time zone','text',Intl.DateTimeFormat().resolvedOptions().timeZone):'');
document.addEventListener('click',async e=>{const button=e.target.closest('[data-action],[data-view]');if(!button)return;if(button.dataset.view){state.view=button.dataset.view;render();window.scrollTo(0,0);return;}const action=button.dataset.action,identifier=button.dataset.id;try{
  if(action==='locale'){state.locale=state.locale==='en'?'fa':'en';localStorage.setItem('relay_locale',state.locale);render();return;}
  if(action==='dismiss'){state.message='';state.error='';render();return;}
  if(action==='login'){await post('/api/login',{userId:identifier});state.view='overview';state.message='';state.error='';await load();return;}
  if(action==='logout'){await post('/api/logout');state.view='overview';state.message='';state.error='';await load();return;}
  if(action==='new-campaign'){modal('Create campaign',field('name','Campaign name')+`<label class="field"><span>Objective</span><select name="objective"><option>traffic</option><option>leads</option><option>awareness</option><option>sales</option></select></label>`+field('budgetMinor','Budget in cents','number','30000','min="1"')+field('destination','Approved HTTPS destination','url','https://example.com/'),d=>post('/api/campaigns',{name:d.name,objective:d.objective,budgetMinor:Number(d.budgetMinor),currency:'USD',destination:d.destination}));return;}
  if(action==='submit'){await post(`/api/campaigns/${identifier}/status`,{status:'submitted'});state.message='Submitted for operator review';await load();return;}
  if(action==='book'){chooseBooking(identifier);return;}
  if(action==='new-property'){modal('Add media property',field('name','Property name')+field('channel','Channel type','text','newsletter')+field('description','Description'),d=>post('/api/properties',d));return;}
  if(action==='new-inventory'){if(!state.properties.length)throw new Error('Add a property first');modal('Add inventory',`<label class="field"><span>Property</span><select name="propertyId">${state.properties.map(p=>`<option value="${p.id}">${escapeHtml(p.name)}</option>`).join('')}</select></label>`+field('name','Inventory name')+field('format','Format','text','newsletter_section')+field('priceMinor','Price in cents','number','12000','min="1"'),d=>post('/api/inventory',{...d,priceMinor:Number(d.priceMinor),currency:'USD'}));return;}
  if(action==='grant-permission'){modal('Record SMS permission',smsFields(false)+field('proofSource','Proof source','text','demo_form')+field('proofText','Permission wording','text','Synthetic test permission'),d=>post('/api/permissions',{...d,channel:'sms'}));return;}
  if(action==='withdraw-permission'){modal('Withdraw SMS permission',smsFields(false),d=>post('/api/permissions/withdraw',d));return;}
  if(action==='sms-preflight'){modal('Preflight test SMS',smsFields(),d=>post('/api/messages/preflight',d).then(r=>{state.message=`SMS ${r.eligible?'eligible':'not eligible'} · ${r.estimate.segments} ${r.estimate.encoding} segment(s) · ${r.permission} permission${r.quietHours?' · quiet hours':''}. Sandbox cost ${money(r.estimate.costMinor,r.estimate.currency)}.`;}));return;}
  if(action==='sms-send'){modal('Record sandbox SMS acceptance',smsFields()+`<p class="field-help">No external SMS is sent. A current permission and non-quiet local hour are required.</p>`,d=>post('/api/messages',{...d,idempotencyKey:crypto.randomUUID()}).then(r=>{state.message=`Sandbox message ${r.status}; provider ID ${r.providerMessageId}. No SMS was sent.`;}));return;}
  if(action==='publish'){modal('Record publication proof',field('proofUrl','Public HTTPS proof URL','url','https://example.com/proof'),d=>post(`/api/bookings/${identifier}/publish`,d).then(result=>{state.message=`Published in sandbox. Tracked link: ${result.trackingUrl}`;}));return;}
  if(action==='conversion'){modal('Import conversion',`<label class="field"><span>Stage</span><select name="stage"><option>lead</option><option>qualified</option><option>opportunity</option><option>won</option><option>refunded</option></select></label>`+field('eventId','Unique event ID','text',crypto.randomUUID())+field('valueMinor','Value in cents','number','0','min="0"'),d=>post('/api/conversions',{bookingId:identifier,stage:d.stage,eventId:d.eventId,valueMinor:Number(d.valueMinor)}));return;}
  if(action==='invoice'){const invoice=await api(`/api/bookings/${identifier}/invoice`);modal('Sandbox invoice',`<p>Invoice ${escapeHtml(invoice.invoiceNumber)}</p><dl class="invoice"><div><dt>Placement</dt><dd>${escapeHtml(invoice.inventory)}</dd></div><div><dt>Total</dt><dd>${money(invoice.totalMinor,invoice.currency)}</dd></div><div><dt>Platform fee</dt><dd>${money(invoice.platformFeeMinor,invoice.currency)}</dd></div><div><dt>Owner payable</dt><dd>${money(invoice.ownerPayableMinor,invoice.currency)}</dd></div><div><dt>Status</dt><dd>${escapeHtml(invoice.status)}</dd></div></dl>`,async()=>{});return;}
  if(action.startsWith('review-')){const [,kind,decision]=action.split('-');await post('/api/review',{kind,id:identifier,decision});state.message=`${kind} ${decision}d`;await load();return;}
  if(['accept','settle','resolve','dispute'].includes(action)){await post(`/api/bookings/${identifier}/${action}`);state.message=`Booking ${action}d in sandbox`;await load();return;}
}catch(error){state.error=error.message;state.message='';render();}});
document.addEventListener('input',event=>{if(event.target.id!=='global-search')return;state.search=event.target.value;const cursor=event.target.selectionStart;render();const input=$('#global-search');input?.focus();input?.setSelectionRange(cursor,cursor);});
load().catch(error=>{$('#app').innerHTML=`<div class="fatal">Could not load sandbox: ${escapeHtml(error.message)}</div>`;});
